usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'pack', 'env', 'token', 'server', 'repo', 'verify')
usage: conda [-h] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'deactivate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'repo', 'token', 'env', 'pack', 'server', 'verify')
no change     /curc/sw/anaconda3/2023.09/condabin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda
no change     /curc/sw/anaconda3/2023.09/bin/conda-env
no change     /curc/sw/anaconda3/2023.09/bin/activate
no change     /curc/sw/anaconda3/2023.09/bin/deactivate
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.sh
no change     /curc/sw/anaconda3/2023.09/etc/fish/conf.d/conda.fish
no change     /curc/sw/anaconda3/2023.09/shell/condabin/Conda.psm1
no change     /curc/sw/anaconda3/2023.09/shell/condabin/conda-hook.ps1
no change     /curc/sw/anaconda3/2023.09/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /curc/sw/anaconda3/2023.09/etc/profile.d/conda.csh
no change     /home/mlippincott@xsede.org/.bashrc
No action taken.
Processing well_fov C11-4 for patient SACRO219
Processing directory  of Segmenting Nuclei
  0%|          | 0/10 [00:00<?, ?it/s] 10%|█         | 1/10 [00:02<00:22,  2.49s/it] 20%|██        | 2/10 [00:03<00:10,  1.33s/it] 30%|███       | 3/10 [00:03<00:06,  1.04it/s] 40%|████      | 4/10 [00:04<00:04,  1.27it/s] 50%|█████     | 5/10 [00:04<00:03,  1.45it/s] 60%|██████    | 6/10 [00:05<00:02,  1.57it/s] 70%|███████   | 7/10 [00:05<00:01,  1.69it/s] 80%|████████  | 8/10 [00:06<00:01,  1.79it/s] 90%|█████████ | 9/10 [00:06<00:00,  1.82it/s]100%|██████████| 10/10 [00:07<00:00,  1.83it/s]100%|██████████| 10/10 [00:07<00:00,  1.40it/s]
Completed Nuclei Segmentation
Segmenting Cells
Completed Cell Segmentation
Segmenting Organoids
  0%|          | 0/25 [00:00<?, ?it/s]  8%|▊         | 2/25 [00:00<00:01, 11.81it/s] 16%|█▌        | 4/25 [00:00<00:01, 10.65it/s] 24%|██▍       | 6/25 [00:00<00:01, 11.31it/s] 32%|███▏      | 8/25 [00:00<00:01, 10.72it/s] 40%|████      | 10/25 [00:00<00:01, 10.43it/s] 48%|████▊     | 12/25 [00:01<00:01, 10.95it/s] 56%|█████▌    | 14/25 [00:01<00:01, 10.56it/s] 64%|██████▍   | 16/25 [00:01<00:00, 11.02it/s] 72%|███████▏  | 18/25 [00:01<00:00, 10.60it/s] 80%|████████  | 20/25 [00:01<00:00, 10.30it/s] 88%|████████▊ | 22/25 [00:02<00:00, 10.76it/s] 96%|█████████▌| 24/25 [00:02<00:00, 10.43it/s]100%|██████████| 25/25 [00:02<00:00, 10.61it/s]
  0%|          | 0/8 [00:00<?, ?it/s] 12%|█▎        | 1/8 [00:02<00:16,  2.32s/it] 25%|██▌       | 2/8 [00:03<00:09,  1.65s/it] 38%|███▊      | 3/8 [00:04<00:06,  1.34s/it] 50%|█████     | 4/8 [00:05<00:05,  1.27s/it] 62%|██████▎   | 5/8 [00:07<00:04,  1.38s/it] 75%|███████▌  | 6/8 [00:08<00:02,  1.38s/it] 88%|████████▊ | 7/8 [00:10<00:01,  1.41s/it]100%|██████████| 8/8 [00:11<00:00,  1.43s/it]100%|██████████| 8/8 [00:11<00:00,  1.44s/it]
Completed Organoid Segmentation
Decoupling nuclei
0it [00:00, ?it/s]2it [00:00,  9.13it/s]3it [00:00,  8.89it/s]5it [00:00, 11.19it/s]7it [00:00, 12.47it/s]9it [00:00, 13.21it/s]11it [00:00, 12.95it/s]
Traceback (most recent call last):
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/4.reconstruct_3D_masks.py", line 372, in <module>
    mask[mask == tmp_df.iloc[i]["original_label"]] = tmp_df.iloc[i]["label"]
                                                     ~~~~~~~~~~~~~~^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'label'
Decoupling cell
0it [00:00, ?it/s]1it [00:00,  2.60it/s]2it [00:01,  1.79it/s]3it [00:02,  1.17it/s]4it [00:03,  1.01it/s]5it [00:04,  1.03s/it]6it [00:05,  1.04s/it]7it [00:06,  1.01it/s]8it [00:07,  1.01it/s]9it [00:08,  1.03it/s]10it [00:09,  1.18it/s]11it [00:09,  1.52it/s]11it [00:09,  1.19it/s]
Decoupling organoid
0it [00:00, ?it/s]1it [00:00,  9.76it/s]3it [00:00,  8.90it/s]4it [00:00,  7.06it/s]5it [00:00,  6.32it/s]6it [00:01,  2.98it/s]7it [00:02,  2.14it/s]8it [00:02,  1.83it/s]9it [00:03,  1.82it/s]11it [00:03,  3.06it/s]11it [00:03,  3.04it/s]
Traceback (most recent call last):
  File "/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/2.segment_images/scripts/5.create_cytoplasm_masks.py", line 74, in <module>
    ).resolve(strict=True)
      ^^^^^^^^^^^^^^^^^^^^
  File "/projects/mlippincott@xsede.org/software/anaconda/envs/GFF_segmentation/lib/python3.11/pathlib.py", line 993, in resolve
    s = os.path.realpath(self, strict=strict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 451, in _joinrealpath
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/alpine1/scratch/mlippincott@xsede.org/GFF_3D_organoid_profiling_pipeline/data/SACRO219/processed_data/C11-4/nuclei_masks_reconstructed.tiff'
Segmentation complete
