Traceback (most recent call last):
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/numpy/_core/arrayprint.py", line 34, in <module>
    from . import numerictypes as _nt
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/numpy/_core/numerictypes.py", line 102, in <module>
    from ._type_aliases import (
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/numpy/_core/_type_aliases.py", line 38, in <module>
    allTypes[_abstract_type_name] = getattr(ma, _abstract_type_name)
AttributeError: module 'numpy.core.multiarray' has no attribute 'signedinteger'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lippincm/Documents/GFF_3D_organoid_profiling_pipeline/3.cellprofiling/scripts/texture.py", line 24, in <module>
    from loading_classes import ImageSetLoader, ObjectLoader
  File "/home/lippincm/Documents/GFF_3D_organoid_profiling_pipeline/3.cellprofiling/scripts/../featurization_utils/loading_classes.py", line 5, in <module>
    import skimage.io
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/skimage/io/__init__.py", line 10, in <module>
    from ._io import *
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/skimage/io/_io.py", line 9, in <module>
    from ..color.colorconv import rgb2gray, rgba2rgb
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/skimage/color/colorconv.py", line 450, in <module>
    rgbcie_from_rgb = rgbcie_from_xyz @ xyz_from_rgb
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/numpy/core/_internal.py", line 855, in array_ufunc_errmsg_formatter
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
  File "/home/lippincm/miniforge3/lib/python3.10/site-packages/numpy/core/_internal.py", line 855, in <listcomp>
    args_string = ', '.join(['{!r}'.format(arg) for arg in inputs] +
RuntimeError: Unable to configure default ndarray.__repr__
